#!/bin/sh

# Example file: ./2015/q3/september/week1.md

cd ${1}

# year
year=`date +%Y`

# quarter
month=`date +%-m`
quarter="q"`python -c "from math import ceil; print int(ceil($month/3.0))"`

# month (lowercase)
monthName=`date +%B | awk '{print tolower($0)}'`

# week
day=`date +%-d`
week=`python -c "from math import ceil; print int(ceil($day/7.0))"`

dir=$year"/"$quarter"/"$monthName
file=$dir"/"week$week".md"

if [ ! -d $dir ]; then
  mkdir -p $dir
fi

timestamp=`date "+%a %b %d - (%-l:%M %p)"`

if [ ! -f $file ]
  then
    touch $file
    echo "## $timestamp">>$file
  else
    echo "\n\n"## $timestamp>>$file
fi

mvim $file
exit 0
