#!/bin/bash

# homebrew
echo Setting up homebrew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# git
echo Setting up git
ssh-keygen -t ed25519 -C "natearmstrong2@gmail.com"
eval "$(ssh-agent -s)"
cp ssh_config ~/.ssh/config
ssh-add -K ~/.ssh/id_ed25519
pbcopy < ~/.ssh/id_ed25519.pub
echo SSH key copied to clipboard
open https://github.com/settings/keys
cp gitignore ~/.gitignore
cp gitconfig ~/.gitconfig

# fonts
echo Setting up fonts
cp fonts/* /Library/Fonts/

# vim
echo Setting up vim
brew install vim
cp vimrc ~/.vimrc
mkdir -p ~/.vim
cp -r colors ~/.vim
vim +PlugInstall +qall
echo Opening MacVim
open https://macvim-dev.github.io/macvim/

# iterm
echo Setting up iTerm
tic iterm/xterm-256color-italic.terminfo

# zsh
echo Setting up zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
cp zshrc ~/.zshrc

